
#This is a basic workflow to help you get started with Actions
#curl "https://www.youtube.com/feeds/videos.xml?playlist_id=PLrggWHcy3azrunmSfTCSlS5JRuB4zTgCY" | jq . > output_file.json

name: GetFeedsHourly5mins

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  schedule:
    - cron:  '5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Download Feed
      run: |-
        
        #curl "https://www.youtube.com/feeds/videos.xml?playlist_id=PLrggWHcy3azrunmSfTCSlS5JRuB4zTgCY" -o feeds/trinity-urc-youtube-worship-services.rss
        curl "https://www.youtube.com/feeds/videos.xml?playlist_id=PLrggWHcy3azp4zpJC_P5iLJB_T87DuYnQ" -o feeds/trinity-urc-youtube-worship-talks-1yearago.rss
        curl "https://www.youtube.com/feeds/videos.xml?playlist_id=PLrggWHcy3azrknrFWHg0UytyE8rLG30Lh" -o feeds/trinity-urc-youtube-blessings.rss
        
    - name: Commit and push changes
      run: |-
        git diff
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        #git diff --quiet || (git add -A && git commit -m "Updated with latest")
        [ ! -z "$(git status --porcelain=v1 2>/dev/null)" ] && (git add -A && git commit -m "Updated with latest")
        git push
